image:
  - Visual Studio 2022
  - Ubuntu2004
platform:
  - x86
  - x64
configuration:
  - Debug

for:
- 
  matrix:
    only:
      - image: Ubuntu2004

  build_script:
    - sh: mkdir build
    - sh: cd build
    - sh: cmake .. -G"Ninja"
    - sh: cmake --build . --config "Debug"
- 
  matrix:
    only:
      - image: Visual Studio 2022

  build_script:
    - cmd: mkdir build
    - cmd: cd build
    - cmd: cmake .. -G"Visual Studio 17"
    - cmd: cmake --build . --config "Debug"